version: 1.0.{build}
branches:
  only:
  - master
environment:
  PATH: '%PATH%;C:\tools\apache-maven-3.3.3\bin'
install:
- cmd: choco upgrade maven
cache:
- C:\tools\apache-maven-3.3.3
- C:\Users\appveyor\.m2
build_script:
- cmd: mvn clean package -DskipTest=true
test_script:
- cmd: mvn test
on_failure:
  - ps: |
     7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'
on_finish:
  - ps: |
     $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $wc = New-Object 'System.Net.WebClient'
      $dirs = Get-ChildItem -Filter surefire-reports -Recurse
      ForEach ($dir in $dirs)
      {
        $files = Get-ChildItem -Path $dir.FullName -Filter TEST-*.xml
        ForEach ($file in $files)
        {
          $wc.UploadFile($url, (Resolve-Path $file.FullName))
        }
      }
